version: "3.7"

services:
  kong-database:
    container_name: kong-database
    image: postgres:9.5
    deploy:
      restart_policy:
        condition: any
    volumes:
      - kong-database-data:/var/lib/postresql/data
    networks:
      - kong-network
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migration-bootstrap:
    container_name: kong-migrations
    build: ./kong
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - kong-network
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
    command: kong migrations bootstrap
      
  kong:
    container_name: kong
    build: ./kong
    networks:
      - kong-network
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8442 ssl http2
      - KONG_REAL_IP_RECURSIVE=on
      - KONG_NGINX_HTTP_RESOLVER=8.8.8.8
      - KONG_PLUGINS=bundled
    ports:
      - "80:8000"
      - "443:8443"
      - "8001:8001"
    healthcheck:
      test: ["CMD", "wget", "-O-", "http://kong:8001/status"]
      interval: 5s
      retries: 10
    restart: on-failure

  konga:
    image: pantsel/konga
    networks:
      - kong-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - kong-database
    environment:
      NODE_ENV: development
    ports:
      - "1337:1337"

  adder:
    container_name: adder
    build: ./adder
    networks:
      - kong-network
    ports:
      - "8081:8080"
    restart: on-failure

  subtractor:
    container_name: subtractor
    build: ./subtractor
    networks:
      - kong-network
    ports:
      - "8082:8080"
    restart: on-failure

  state:
    container_name: state
    build: ./state
    networks:
      - kong-network
    ports:
      - "8083:8080"
    restart: on-failure


volumes:
  kong-database-data:
    driver: local

networks:
  kong-network:
    external: false

